global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server:3000']
    scrape_interval: 5s

  - job_name: 'ai_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai_service:5000']
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: "http://remote-storage:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 200
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_shards: 1
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms

remote_read:
  - url: "http://remote-storage:9201/read"
    read_recent: true
    required_matchers:
      job: backend

alert_relabel_configs:
  - source_labels: [severity]
    regex: '(.*)'
    target_label: severity
    replacement: '$1'

scrape_config_files:
  - 'prometheus_*.yml'

storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 50GB
    wal:
      retention:
        time: 12h

query_log_file: /prometheus/query.log